apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-decision-service-config
data:
  PORT: "3002"
  NODE_ENV: "production"
  {{- range $key, $val := .Values.decisionService.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
