apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-decision-service
spec:
  type: ClusterIP
  selector:
    app: decision-service
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
