apiVersion: v1
kind: Service
metadata:
  name: telco-intel-service
  namespace: signalrisk
  labels:
    app: telco-intel-service
spec:
  selector:
    app: telco-intel-service
  ports:
  - port: 3007
    targetPort: 3007
    protocol: TCP
  type: ClusterIP
