apiVersion: v1
kind: Service
metadata:
  name: rule-engine-service
  namespace: signalrisk
  labels:
    app: rule-engine-service
spec:
  selector:
    app: rule-engine-service
  ports:
  - port: 3008
    targetPort: 3008
    protocol: TCP
  type: ClusterIP
