apiVersion: v1
kind: Service
metadata:
  name: network-intel-service
  namespace: signalrisk
  labels:
    app: network-intel-service
spec:
  selector:
    app: network-intel-service
  ports:
  - port: 3006
    targetPort: 3006
    protocol: TCP
  type: ClusterIP
