apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-feature-flag-service
spec:
  type: ClusterIP
  selector:
    app: feature-flag-service
  ports:
    - port: 3013
      targetPort: 3013
      protocol: TCP
