apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-auth-service-config
data:
  PORT: "3001"
  NODE_ENV: "production"
  {{- range $key, $val := .Values.authService.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
