apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-auth-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-auth-service
  minReplicas: {{ .Values.defaults.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.defaults.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.defaults.autoscaling.targetCPUUtilizationPercentage }}
