apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-event-collector
  labels:
    app: event-collector
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.eventCollector.replicaCount | default .Values.defaults.replicaCount }}
  selector:
    matchLabels:
      app: event-collector
  template:
    metadata:
      labels:
        app: event-collector
    spec:
      containers:
        - name: event-collector
          image: "{{ .Values.global.imageRegistry }}/event-collector:{{ .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.defaults.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-event-collector-config
            - secretRef:
                name: {{ .Release.Name }}-event-collector-secrets
                optional: true
