apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-telco-intel-service
spec:
  type: ClusterIP
  selector:
    app: telco-intel-service
  ports:
    - port: 3007
      targetPort: 3007
      protocol: TCP
