apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-network-intel-service
spec:
  type: ClusterIP
  selector:
    app: network-intel-service
  ports:
    - port: 3006
      targetPort: 3006
      protocol: TCP
