apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-behavioral-service
spec:
  type: ClusterIP
  selector:
    app: behavioral-service
  ports:
    - port: 3005
      targetPort: 3005
      protocol: TCP
